name: app_reciclaje_cat
description: "Sistema de control de descontaminación para centros CAT."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Iconos oficiales de iOS
  cupertino_icons: ^1.0.2

  # Persistencia de datos (Trabajadores, Marcas, Configuración)
  shared_preferences: ^2.2.2
  
  # Gestión de base de datos local
  sqflite: ^2.3.0
  path: ^1.8.3

  # Firma táctil del operario
  signature: ^5.4.0

  # Generación de informes PDF
  pdf: ^3.10.8
  
  # Impresión y compartir archivos (WhatsApp, Email, Drive)
  printing: ^5.11.1

  # Acceso a carpetas del sistema
  path_provider: ^2.1.1

  # Selector de imágenes (para el logo del CAT)
  image_picker: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # Si vas a incluir el logo como un archivo fijo, descomenta las líneas de abajo
  # assets:
  #   - assets/logo.png
